// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollIO.Data.Context;

namespace PollIO.Data.Migrations
{
    [DbContext(typeof(PollDbContext))]
    [Migration("20200803103322_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PollIO.Business.Models.OptionsPoll", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<string>("Votes")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("OptionsPolls");
                });

            modelBuilder.Entity("PollIO.Business.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Poll_description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Views")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("PollIO.Business.Models.OptionsPoll", b =>
                {
                    b.HasOne("PollIO.Business.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
